WebApplication2 - copia/Models/Especialidad.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Especialidad()
        {
            this.Doctor = new HashSet<Doctor>();
        }
    
        public int IIDESPECIALIDAD { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctor { get; set; }
    }
}

WebApplication2 - copia/Controllers/EspecialidadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;
using WebApplication2.Clases;

namespace WebApplication2.Controllers
{
    public class EspecialidadController : Controller
    {
        // GET: Especialidad
        public ActionResult Index(EspecialidadCLS  oEspecialidadCLS)
        {
            List<EspecialidadCLS> listaEspecialidad = new List<EspecialidadCLS>();
            //ViewBag.Mensaje = "Estoy pasando un mensaje del controller a la vista";
            using (BDHospitalEntities1 db = new BDHospitalEntities1())
            {
                if (oEspecialidadCLS.nombre == null || oEspecialidadCLS.nombre == "")
                {

                    listaEspecialidad = (from especialidad in db.Especialidad
                                         where especialidad.BHABILITADO == 1
                                         select new EspecialidadCLS
                                         {
                                             iidespecialidad = especialidad.IIDESPECIALIDAD,
                                             nombre = especialidad.NOMBRE,
                                             descripcion = especialidad.DESCRIPCION
                                         }).ToList();
                    ViewBag.nombreEspecialidad = "";
                }
                else
                {

                    listaEspecialidad = (from especialidad in db.Especialidad
                                         where especialidad.BHABILITADO == 1
                                         && especialidad.NOMBRE.Contains(oEspecialidadCLS.nombre)
                                         select new EspecialidadCLS
                                         {
                                             iidespecialidad = especialidad.IIDESPECIALIDAD,
                                             nombre = especialidad.NOMBRE,
                                             descripcion = especialidad.DESCRIPCION
                                         }).ToList();
                    ViewBag.nombreEspecialidad = oEspecialidadCLS.nombre;

                }
            
            }
                return View(listaEspecialidad);
        }
    }
}

WebApplication2 - copia/Views/Especialidad/Index.cshtml
@using WebApplication2.Clases;

@model IEnumerable<EspecialidadCLS>
@{
    ViewBag.Title = "Index";
    //string mensaje = ViewBag.Mensaje;
    string nombreEspecialidad = ViewBag.nombreEspecialidad;
}
@*<h1>@mensaje</h1>*@
<p></p>
<form asp-controller="Especialidad" asp-action="Index" method="post" class="mb-2"
      style="display:grid;grid-template-columns:1fr 2fr 1fr 1fr" id="frmFormulario">
    <label>Ingrese nombre especialidad</label>
    <input type="text" id="nombre" class="rom form-control" name="nombre" value="@nombreEspecialidad" />
    <input type="submit" value="Buscar" class="btn btn-info" />
    <input type="button" value="Limpiar" class="btn btn-danger" onclick="Limpiar()" />
</form>
    

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Id Especialidad</th>
            <th>Nombre</th>
            <th>Descripcion</th>
           
        </tr>
    </thead>
    <tbody>
        @foreach (EspecialidadCLS oEspecialidad in Model)
        { 
            <tr>
                <td>@oEspecialidad.iidespecialidad</td>
                <td>@oEspecialidad.nombre</td>
                <td>@oEspecialidad.descripcion</td>
            </tr>
        
        }
    </tbody>
</table>

<script>
    function Limpiar() {
        document.getElementById("nombre").value = "";
        document.getElementById("frmFormulario").submit();
    }
</script>