WebApplication2 - copia/Models/TipoUsuario.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoUsuario()
        {
            this.TipoUsuarioPagina = new HashSet<TipoUsuarioPagina>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IIDTIPOUSUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoUsuarioPagina> TipoUsuarioPagina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}

WebApplication2 - copia/Controllers/TipoUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Clases;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class TipoUsuarioController : Controller
    {
        // GET: TipoUsuario
        public ActionResult Index( TipoUsuarioCLS oTipoUsuarioCLS)
        {
            List<TipoUsuarioCLS> listaTipoUsuario = new List<TipoUsuarioCLS>();
            using (BDHospitalEntities1 db = new BDHospitalEntities1())
            { 
                listaTipoUsuario = (from tipoUsuario in db.TipoUsuario
                                    where tipoUsuario.BHABILITADO==1
                                    select new TipoUsuarioCLS
                                    {
                                     iidTipoUsuario = tipoUsuario.IIDTIPOUSUARIO,
                                        nombre = tipoUsuario.NOMBRE,
                                        descripcion = tipoUsuario.DESCRIPCION


                                    }).ToList();
                if (oTipoUsuarioCLS.nombre == null && oTipoUsuarioCLS.descripcion == null
                    && oTipoUsuarioCLS.iidTipoUsuario == 0)
                {
                    ViewBag.Nombre = "";
                    ViewBag.Descripcion = "";
                    ViewBag.iidTipoUsuario = "";
                
                }
            
            }


                return View(listaTipoUsuario);
        }
    }
}

WebApplication2 - copia/Views/TipoUsuario/Index.cshtml
@model IEnumerable<WebApplication2.Clases.TipoUsuarioCLS>

@{
    ViewBag.Title = "Index";
 string nombre =   ViewBag.Nombre;
  string descripcion =  ViewBag.Descripcion;
  int iidtipousuario =   ViewBag.iidTipoUsuario;
}

<h2>Index</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<from asp-controller="TipoUsuario" asp-action="Index">
    <input type="submit" value="Enviar" class="btn btn-primary" />
           <table  style="color:black" class="table" >
        <thead class="table-bordered" >
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.iidTipoUsuario)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.descripcion)
                </th>
                <th></th>
            </tr>

            <tr>
                <th>
                    <input type="number" name="iidTipoUsuario" class="from from-control" />
                </th>
                <th>
                    <input type="text" name="nombre" class="from from-control" />
                </th>
                <th>
                    <input type="text" name="descripcion" class="from from-control" />
                </th>
                <th></th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.iidTipoUsuario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }

    </table>
</from>