WebApplication2 - copia/Models/Sede.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sede
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sede()
        {
            this.Cita = new HashSet<Cita>();
            this.Doctor = new HashSet<Doctor>();
        }
    
        public int IIDSEDE { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctor { get; set; }
    }
}

WebApplication2 - copia/Controllers/SedeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Clases;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class SedeController : Controller
    {
        // GET: Sede
        public ActionResult Index(SedeCLS oSedeCLS)
        {
            List<SedeCLS> listaSede = new List<SedeCLS>();
            using (BDHospitalEntities1 bd = new BDHospitalEntities1())
            {
                if (oSedeCLS.nombreSede == "" || oSedeCLS.nombreSede == null)
                {
                    listaSede = (from sede in bd.Sede
                                 where sede.BHABILITADO == 1
                                 select new SedeCLS
                                 {
                                     iidSede = sede.IIDSEDE,
                                     nombreSede = sede.NOMBRE,
                                     direccion = sede.DIRECCION

                                 }).ToList();
                    ViewBag.nombreSede = "";
                }
                else
                {
                    listaSede = (from sede in bd.Sede
                                 where sede.BHABILITADO == 1
                                 && sede.NOMBRE.Contains(oSedeCLS.nombreSede)
                                 select new SedeCLS
                                 {
                                     iidSede = sede.IIDSEDE,
                                     nombreSede = sede.NOMBRE,
                                     direccion = sede.DIRECCION

                                 }).ToList();
                    ViewBag.nombreSede = oSedeCLS.nombreSede;
                }


            }

            return View(listaSede);
        }
    }
}

WebApplication2 - copia/Views/Sede/Index.cshtml
@using WebApplication2.Clases;
@model IEnumerable<WebApplication2.Clases.SedeCLS>

@{
    ViewBag.Title = "Index";
    string nombreSede = ViewBag.nombreSede;
}

<h2>Index</h2>
<form id="frmEnviar" asp-controller="Sede" asp-action="Index" class="mb-2"
      method="post">
    <label>Ingrese el nombre Sede</label>
    <input type="text" class="form-control form-control" name="nombreSede"
           onkeyup="Buscar()" | value="@nombreSede"/>
</form>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.iidSede)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombreSede)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.direccion)
        </th>
        <th></th>
    </tr>

    @foreach (SedeCLS item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.iidSede)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombreSede)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.direccion)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }

</table>
<script>
    function Buscar() {
        document.getElementById("frmEnviar").submit();

    }
</script>